### ISSUE TITLE
Merging scripts

### ISSUE THREAD

**Issue by zombiefied** [DeastinY/CoffeeRecommendationBot#10]
It isn't really neccessary to have two different scripts, merging them would make this a bit more pythonistic ;)

**Comment by zombiefied** [comment]
I've got a file i'd like to push, but i'm not really gitsavvy, how would I do about making a pull request? @DeastinY

**Comment by DeastinY** [comment]
1. Fork the project (did you already do that ?)
2. Push to the fork (a copy of the project on your account)
3. Click the commit and there is a Pull Request button at the top

**Comment by zombiefied** [comment]
Thanks, figured that out, a pull request is on it's way.

**Comment by DefCon-007** [comment]
Created the pull request #39
